### ISSUE TITLE
Plenty of issues with Docker compose

### ISSUE THREAD

**Issue by igorjos** [Notifuse/notifuse#72]
I'm using the latest docker image with the following config. 

```
services:
  app:
    image: notifuse/notifuse:latest
    container_name: notifuse_api
    ports:
      - '127.0.0.1:8091:8080'
    environment:
      # Server Configuration
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      ENVIRONMENT: production
      # Database Configuration (Required)
      DB_HOST: cc-postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: notifuse
      DB_SSLMODE: disable
      SECRET_KEY: key
      ROOT_EMAIL: info@email
    restart: unless-stopped
    volumes:
      - /var/tmp/notifuse:/app/data           
    networks:
      - shared_network

networks:
  shared_network:
    external: true
```

When I run it on for a first run, there are plenty of issues.
1. if there is # in any of the environment variables then it breaks so using any values where # is included is not an option.
2. After the first start and setting SMTP (testing it to work) - the magic code never arrives - the app throws an error that Notifuse user can't send an email. Restarting the container seems to solve the issue.
3. Create workspace is the place from where app can't move further. Submitting the form returns 500 error and saying it can't write to DB, while when I check the workspaces table the record is there. Also duplicate records (same workspace id) is allowed.
4. If you manage to pass the workspace creation screen (which I did somehow magically) there are plenty of new 500 errors for missing permissions to write in DB etc. while the user used for DB connection have all rights granted..

Note: I'm not building a version locally from git code, instead I'm using the image from docker repository.
P.S my postgres instance runs as individual container in the same "shared_network" so access to the database, creation of the tables is not an issue at all.

**Comment by pierre-b** [comment]
hi, could you please share what platform are you using to deploy the docker compose so we can try to reproduce it?

also could you please share a screenshot of the api logs?

without logs I won't be able to assist much 🙏

**Comment by igorjos** [comment]
Hi I'm using a linux (debian and ubuntu the same issue). 
Docker version 28.4.0, build d8eb465. 
PSQL v13.1

On the first run:
```
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Starting API server on 0.0.0.0:8080"}
notifuse_api  | {"level":"info","version":"13.7","time":"2025-10-27T11:28:37Z","message":"Starting Notifuse application"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Connecting to database cc-postgres:5432, user notifuse, sslmode disable, password: d...u, dbname: notifuse"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"System database check completed"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Starting migration process"}
notifuse_api  | {"level":"info","db_version":"13","code_version":"13","time":"2025-10-27T11:28:37Z","message":"Version comparison"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Database is up to date, no migrations needed"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Setup wizard required - installation not complete"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Using SMTP mailer for production"}
notifuse_api  | {"level":"info","task_type":"send_broadcast","time":"2025-10-27T11:28:37Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Broadcast orchestrator registered with task service"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"TaskService subscribed to broadcast events"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"System notification service registered with event bus"}
notifuse_api  | {"level":"info","task_type":"build_segment","time":"2025-10-27T11:28:37Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","task_type":"check_segment_recompute","time":"2025-10-27T11:28:37Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","task_type":"process_contact_segment_queue","time":"2025-10-27T11:28:37Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Application successfully initialized"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Server started successfully"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:28:37Z","message":"Graceful shutdown middleware enabled"}
notifuse_api  | {"level":"info","address":"0.0.0.0:8080","api_endpoint":"","port":8080,"time":"2025-10-27T11:28:37Z","message":"Server starting on 0.0.0.0:8080 with API endpoint: "}

notifuse_api  | {"level":"info","email":"email_address_masked_manually","time":"2025-10-27T11:29:24Z","message":"Root user already exists, skipping creation"}
notifuse_api  | {"level":"info","email":"email_address_masked_manually","time":"2025-10-27T11:29:24Z","message":"Setup wizard completed successfully"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:29:24Z","message":"Reloading configuration from database..."}
notifuse_api  | {"level":"info","time":"2025-10-27T11:29:24Z","message":"Configuration reloaded successfully - PASETO keys will be reloaded on next use"}
notifuse_api  | {"level":"error","user_id":"83417a0d-06c7-44ba-88ad-747860b9f515","email":"email_address_masked_manually","error":"failed to set email from address: failed to parse mail address \"\\\"Notifuse\\\" <>\": mail: invalid string","time":"2025-10-27T11:29:42Z","message":"Failed to send magic code"}
```

Then I stop the docker container and I restart it again:

```
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Starting API server on 0.0.0.0:8080"}
notifuse_api  | {"level":"info","version":"13.7","time":"2025-10-27T11:32:46Z","message":"Starting Notifuse application"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Connecting to database cc-postgres:5432, user notifuse, sslmode disable, password: d...u, dbname: MASKED_NAME"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"System database check completed"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Starting migration process"}
notifuse_api  | {"level":"info","db_version":"13","code_version":"13","time":"2025-10-27T11:32:46Z","message":"Version comparison"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Database is up to date, no migrations needed"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"System installation verified"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Using SMTP mailer for production"}
notifuse_api  | {"level":"info","task_type":"send_broadcast","time":"2025-10-27T11:32:46Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Broadcast orchestrator registered with task service"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"TaskService subscribed to broadcast events"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"System notification service registered with event bus"}
notifuse_api  | {"level":"info","task_type":"build_segment","time":"2025-10-27T11:32:46Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","task_type":"check_segment_recompute","time":"2025-10-27T11:32:46Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","task_type":"process_contact_segment_queue","time":"2025-10-27T11:32:46Z","message":"Registered task processor"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Application successfully initialized"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Server started successfully"}
notifuse_api  | {"level":"info","time":"2025-10-27T11:32:46Z","message":"Graceful shutdown middleware enabled"}
notifuse_api  | {"level":"info","address":"0.0.0.0:8080","api_endpoint":"URL_MASKED_MANUALLY","port":8080,"time":"2025-10-27T11:32:46Z","message":"Server starting on 0.0.0.0:8080 with API endpoint: URL_MASKED_MANUALLY"}

# CREATE A NEW WORKSPACE
notifuse_api  | {"level":"error","workspace_id":"test","error":"failed to create workspace database: pq: permission denied to create database","time":"2025-10-27T11:34:35Z","message":"Failed to create workspace"}
```

This is where it stuck. If I go and add the workspace in db manually then I can get to the next screen and nothing from there.

The access to the DB works well, being able to set smtp data, paseto keys etc, means all is good, as well I did grant all to the user so there are no limitations.

**Comment by pierre-b** [comment]
thanks I'll investigate asap, I'm traveling back to home today, will arrive in 2 days🙏

**Comment by igorjos** [comment]
> thanks I'll investigate asap, I'm traveling back to home today, will arrive in 2 days🙏

sure no worries. 

Additional hint which might help is: I have created a user using psql CLI commands, and granted all permissions, with this the db is created but afterwards the errors are as shown.

When I open on Mac locally (docker image as well) I had the issues as above, but then I created a user using pgAdmin , set the user as super user and everything seemed to work well.

=== EDIT === 

I did some further edits and debugging, it turned out if the role of the PSQL user is set to SUPERUSER then the DB issues are all resolved, just the first issue with sending an email with magic link fails.

The app shouldn't use superuser, because it poses a security risk if deployed on a shared database instance.

**Comment by pierre-b** [comment]
The https://github.com/Notifuse/notifuse/releases/tag/v14.0 is now live and provides a new Setup Wizard. Also, using Postgresql 17 is mandatory.

Could you please try it and let me know what errors remain?

**Comment by pierre-b** [comment]
Actually I released a very important update for security: https://github.com/Notifuse/notifuse/releases/tag/v15.0

**Comment by igorjos** [comment]
@pierre-b I did took the latest version, and the issue with the postgres user permissions are still existing. As I see the problem is created because the user needs permissions to create new databases.. e.g notifuse_ws_WORKSPACE_ID - which is a bit strange why would the app create many different databases. 

As a hint only, if anyone tries to deploy this on Heroku or similar platforms, this will not work, because the user there can have only one database and it is now allowed to create other databases.

For me this is a no-go, especially if the app fails on security (which I can't control) anyone who get access to the DB user can create new databases etc. 

For the magic link, now SMTP connection works, server restarts itself and it fails to send email with an timeout error. When I try to do everything from scratch again, the same happens, the connection is ok, sending of email fails with timeout, while the server settings are still the same as when I was testing with previous versions of the app.

I hope this was helpful.

**Comment by pierre-b** [comment]
Thanks @igorjos for the feedback,

Notifuse has been designed to scale for millions on rows/messages, and for that reason it's mandatory to put each workspace in it's dedicated database to preserve the tables performance (locks concurrency, buffers, indexes...) among workspaces.

If you already know the workspace id you gonna use, you can create your system db `notifuse_system` and workspace db using the format `notifuse_ws_workspaceid` and give your Postgres user credentials over these databases before installing Notifuse.

The server settings can be stored in 2 places:
- in env var (check your docker compose or .env etc...)
- the database `notifuse_system`

If you see that server settings are same as a previous deployment, I guess you should delete the Notifuse tables first before installing a fresh version with correct settings.

If the SMTP timeout persists, I would like to see logs and get more details about the kind of SMTP server you are using (with TLS or not, with user/pass or not etc...). I strongly recommend to use a free Mailgun/Postmark SMTP for system emails.

Let me know if things are not clear, I'll do my best to help!

**Comment by igorjos** [comment]
Hi @pierre-b  thanks for the feedback. I understand the above explained. 
I'm always testing on new database (drop the old one, create new, then run the docker image - so no old values are used).
The issue with SMTP happens when one docker image is trying to communicate with the other (in my setup SMTP runs in docker as well) so when Notifuse docker image tries to connect to SMTP docker image it fails. 

Anyhow these are probably edge cases, which might serve as documentation if someone land to the same issues - hope it give clarity for resolution.

I will close the ticket. 
Thanks for the updates.

**Comment by pierre-b** [comment]
Ah I see, it looks like intra-docker communication fails between containers for your SMTP, probably a port that's not open or invalid hostname (localhost vs 0.0.0.0). Can't help you more at this level.
